name: build
# 触发 workflow 的事件
on: push
# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build-back
  build:
    #运行在最新版ubuntu系统中
    runs-on: ubuntu-latest
    #步骤合集
    steps:
    # 拉取最新提交的代码
    - name: pull new code
    - uses: actions/checkout@v3
    # 设置编译环境为nodejs-16.14.2
    - name: set Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'
    # 切换工作目录
      run: cd nestjs
      run: npm install
      run: npm build
    # 切换工作目录
      run: cd ../vuethree
      run: npm install
      run: npm build
    