name: build
# 触发 workflow 的事件
on: push
# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build-back
  build:
    #运行在最新版ubuntu系统中
    runs-on: ubuntu-latest
    #步骤合集
    steps:
    # 切换到指定的目录
    - name: Change Working Directory
      run: cd nestjs/
      #使用checkout@v3这个action
    - uses: actions/checkout@v3
      #新建一个名为 actions/checkout@v3 的步骤
    - name: Use Node.js 16.14.2
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'
    - run: npm install
    - run: npm run build
    - name: Change Working Directory
      run: cd vuethree/
      run: npm install
      run: npm run build