name: build
# 触发 workflow 的事件
on: push
# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build-back
  build:
    #运行在最新版ubuntu系统中
    runs-on: ubuntu-latest
    #步骤合集
    steps:
    # 拉取最新提交的代码
    - uses: actions/checkout@v3
    # 设置编译环境为nodejs-16.14.2
    - uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'
    # 编译后端项目
    - name: build back
      run: |
        cd nestjs
        npm install
        npm run build
    # 编译前端项目
    - name: build web
      run: |
        cd vuethree
        npm install
        npm run build
    # 压缩
    - name: zip project
      run: |
        mkdir back
        cp -r nestjs/dist back
        cp -r nestjs/node_modules back
        mkdir web
        cp -r vuethree/dist web
        zip -r develop.zip back web
    # 上传服务器
    - uses: appleboy/scp-action@v0.1.4
      with:
        host: mike-hd123.tk
        username: ubuntu
        key: ${{ secrets.SERVER_KEY }}
        port: 22
        source: 'develop.zip'
        target: '~'