name: build
# 触发 workflow 的事件
on: push
# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build-back
  build:
    #运行在最新版ubuntu系统中
    runs-on: ubuntu-latest
    #步骤合集
    steps:
      #使用checkout@v3这个action
    - uses: actions/checkout@v3
      # Set up Node.js 
    - name: set Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'
    - name: Change Working Directory
      run: cd nestjs
    - name: Install
      run: npm install
    - name: Build
      run: npm build
    - name: Change Working Directory
      run: cd ../vuethree
    - name: Install
      run: npm install
    - name: Build
      run: npm build
    