name: build
# 触发 workflow 的事件
on: push
# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build
  build:
    #运行在最新版ubuntu系统中
    runs-on: ubuntu-latest
    #步骤合集
    steps:
      #新建一个名为 install node 的步骤
      - name: install node
        #执行执行某个shell命令或脚本
        run: |
          apt install node-16
        env:
          server: mike-hd123.tk